### ISSUE TITLE
Wait=true does not appear to be working as intended...

### ISSUE THREAD

**Issue by calexandre** [gavinbunney/terraform-provider-kubectl#109]
According to the documentation, the `wait` property when set like `wait=true` should wait for a given resource to be properly destroyed right?

My `namespace` (and some other kind of resources) have specific finalizers that take their time to complete, but when using this provider, it just seems to delete resources in a *fire-and-forget* fashion which is not desired. I can confirm this "erratic" behavior, because when I manually delete the namespace using `kubectl` cli, it sits there waiting for the namespace to be deleted before returning...

Am I missing something, or the `wait` function is not working as intended?

Tested on terraform `0.14.x` and `0.15.x`.

Thanks!

**Comment by vrabbi** [comment]
doesnt work for me either.

**Comment by linuxbsdfreak** [comment]
Same here. I created a ticket https://github.com/gavinbunney/terraform-provider-kubectl/issues/41

**Comment by alekc** [comment]
@calexandre @vrabbi if you are willing to try a patched version while waiting for the PR to be merged
```
terraform {
  required_version = ">= 1.0"
  required_providers {
   
    kubectl = {
      // keep override until https://github.com/gavinbunney/terraform-provider-kubectl/issues/109 is merged and released
      #      source  = "gavinbunney/kubectl"
      #      version = ">= 1.13.0"
      version = "1.13.1-1"
      source  = "alekc-forks/kubectl"
    }
  }
}
```

**Comment by calexandre** [comment]
> @calexandre @vrabbi if you are willing to try a patched version while waiting for the PR to be merged
> 
> ```
> terraform {
>   required_version = ">= 1.0"
>   required_providers {
>    
>     kubectl = {
>       // keep override until https://github.com/gavinbunney/terraform-provider-kubectl/issues/109 is merged and released
>       #      source  = "gavinbunney/kubectl"
>       #      version = ">= 1.13.0"
>       version = "1.13.1-1"
>       source  = "alekc-forks/kubectl"
>     }
>   }
> }
> ```

Already spinning up a cluster to try it out ;)

**Comment by calexandre** [comment]
> @calexandre @vrabbi if you are willing to try a patched version while waiting for the PR to be merged
> 
> ```
> terraform {
>   required_version = ">= 1.0"
>   required_providers {
>    
>     kubectl = {
>       // keep override until https://github.com/gavinbunney/terraform-provider-kubectl/issues/109 is merged and released
>       #      source  = "gavinbunney/kubectl"
>       #      version = ">= 1.13.0"
>       version = "1.13.1-1"
>       source  = "alekc-forks/kubectl"
>     }
>   }
> }
> ```

I'm sorry @alekc but it doesn't seem to be working :(
I have the exact the same behaviour as before...

I tested with a simple `namespace` creation/deletion.

Here's the `terraform destroy` for the namespace resource

```bash
➜ tf apply plan.tfplan      
module.kubectl_provider_test.kubectl_manifest.manifests[0]: Destroying... [id=/api/v1/namespaces/test]
module.kubectl_provider_test.kubectl_manifest.manifests[0]: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

I immediately queried the the list of namespaces with `kubectl`

```bash
➜ k get namespaces
NAME              STATUS        AGE
default           Active        3h27m
kube-node-lease   Active        3h27m
kube-public       Active        3h27m
kube-system       Active        3h27m
test              Terminating   32s
```

As you can see, right after terraform completed, the namespace is still in a terminating state.

Am I missing something?

**Comment by calexandre** [comment]
I also like to add that you can easily replicate the correct behaviour with `kubectl`:

```bash
➜ k create namespace test      
namespace/test created

➜ k delete namespace test         
namespace "test" deleted

➜ k get namespaces       
NAME              STATUS   AGE
default           Active   3h41m
kube-node-lease   Active   3h41m
kube-public       Active   3h41m
kube-system       Active   3h41m
```

**Comment by alekc** [comment]
@calexandre weird, it's working on my end. Did you put a "wait=true" on the resource?  can you paste your hcl for the ns and check that in terraform init output you have `1.13.1-1` version loaded up.

**Comment by calexandre** [comment]
> @calexandre weird, it's working on my end. Did you put a "wait=true" on the resource? can you paste your hcl for the ns and check that in terraform init output you have `1.13.1-1` version loaded up.

![facepalm](https://c.tenor.com/Oaq1HNMNDVsAAAAC/facepalm-crowd.gif)

You are right. I totally forgot the `wait=true`...
I confirm that it is working and it waits for the resource to be terminated...

Thank you!

**Comment by alekc** [comment]
I dont see a PR related to jimmy-scott version, but from the description on the ticket it waits for an attribute? Here is a bit different scenario because we are waiting for deletion (and once the object is deleted we can't read attribute from it).

**Comment by linuxbsdfreak** [comment]
@alekc  Thx. Sorry i got it mixed up. I want the other feature defined  here https://github.com/gavinbunney/terraform-provider-kubectl/issues/41

**Comment by alekc** [comment]
@linuxbsdfreak I've added support for wait_for in my forked provider (at the end I've decided to move my development there given the lack of interest from the owner to merge previous pr) https://registry.terraform.io/providers/alekc/kubectl/latest/docs/resources/kubectl_manifest#with-explicit-wait_for

**Comment by stevehipwell** [comment]
@alekc does `wait = true` work correctly in your version? And secondly are you willing to take PRs on your fork (https://github.com/gavinbunney/terraform-provider-kubectl/pull/149)?

**Comment by alekc** [comment]
Yes, it has https://github.com/alekc/terraform-provider-kubectl/commit/22c5121306220e711e1af4dca5acb7537f2d5362 in it. 

Feel free to drop a PR, but keep in mind that I've recently updated the dependencies (https://github.com/alekc/terraform-provider-kubectl/commit/bd4999d82c02316b3dd325953937e5324a746021) so you might need to retest it in case it's behaviour has been changed.

**Comment by alekc** [comment]
In case anyone stumbs here on this issue from google. The fix has been merged to the master, but it was never released. 

You can use my forked (and maintained) version on 
```
terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
      version >= "2.0.2"
    }
  }
}
```
