### ISSUE TITLE
yaml_body source from template file failing to apply without ay errors 

### ISSUE THREAD

**Issue by chrisadkin** [gavinbunney/terraform-provider-kubectl#116]
I'm using:

Kubernetes 1.20.7 
Terraform    1.0
Kubectl provider 1.11.1

I have the following configuration:
```
terraform {
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.11.1"
    }
  }
}

provider "kubectl" {}

resource "kubectl_manifest" "sa_login_secret" {
  yaml_body = templatefile("${path.module}/templates/sa_login_secret.tpl", {
    username = var.sa_username
    password = var.sa_password
    name     = var.sa_secret_name
  })
}

resource "kubectl_manifest" "azure_arc_sql_mi" {
  yaml_body = templatefile("${path.module}/templates/azure_arc_sql_mi.tpl", {
    instance_name           = var.instance_name
    namespace               = var.namespace
    cpu_limit               = var.cpu_limit
    memory_limit            = var.memory_limit
    cpu_request             = var.cpu_request
    memory_request          = var.memory_request
    service_type            = var.service_type
    backup_storage_class    = var.backup_storage_class
    data_storage_class      = var.data_storage_class
    data_logs_storage_class = var.data_logs_storage_class
    logs_storage_class      = var.logs_storage_class
  })

  depends_on = [
    kubectl_manifest.sa_login_secret
  ]
}
```

When I change this such that actual static files are created via local_file resources and use these with kubectl create -n <namespace> -f <file> everything works, but when I attempt to use the output directly from templatefile, terraform apply works as inspected according to its output, I look inside my cluster for the objects I now expect to be there - and I do not see these.

**Comment by jodem** [comment]
@chrisadkin the kubectl_manifest is expecting a **single document yaml** (not a yaml with multiple kube sections like namespace + deployment + pod + ingress rule , the _---_ separation). It ignores the other documents (with no notifications). If you want to deploy multiple document you should use the kubectl_path_documents, or deploy in multiple manifests.

```

data "kubectl_path_documents" "nginx_manifests" {
  pattern = "./templates/deploy_nginx.yaml"
  vars = {
    domainName = "joce"
  }
}

resource "kubectl_manifest" "deploy_nginx" {
  count     = length(data.kubectl_path_documents.nginx_manifests.documents)
  yaml_body = element(data.kubectl_path_documents.nginx_manifests.documents, count.index)
}
```

**Comment by viyh** [comment]
This was not the behavior in the past and broke our configuration. With a previous version of the provider, it worked with multiple sections within one YAML doc. Is it possible to make that work again?

**Comment by gavinbunney** [comment]
As jodem mentioned, it needs to be a single manifest per apply. The `kubectl_path_documents` data source was created to make this easy :)
