### ISSUE TITLE
Is it possible to delete an existing resource ?

### ISSUE THREAD

**Issue by Smana** [gavinbunney/terraform-provider-kubectl#122]
Hi everyone, 

I'm currently trying to find out the best way to remove a resource that is being deployed by default on EKS clusters.
Indeed in order to install another CNI plugin I'd like to remove the `aws-node` deamonset.

What's the best way to achieve that and is it possible with this provider please?

Thank you!

**Comment by citrix-ericgo** [comment]
Sounds like someone is trying to nuke `eks.privileged`. I would also be interested in this.

**Comment by gavinbunney** [comment]
Not directly there isn't, as Terraform generally relies on knowing the state of the world before being able to reason about what to do.

The way I've handled similar situations before was to put some generalized `kubectl delete <>` operations in a shell script, then call it from a `null_resource` `local-exec` provisioner block
