### ISSUE TITLE
[Feature Request] Please allow reconfigure during retrials

### ISSUE THREAD

**Issue by devprojectsme** [gavinbunney/terraform-provider-kubectl#128]
Dear @gavinbunney

in your comment(see [here](https://github.com/gavinbunney/terraform-provider-kubectl/issues/63#issuecomment-775525931)) you provide the option to execute your provider with predefined host and cert provides as Terrafrom values. This however means, one need a separate "terraform apply" with already existing EKS cluster. 

As the terraform requires the provider configuration in the root module, this approach excludes the option to create the EKS and deploy some manifests in one iteration, as the provider is initialized before the cluster is created, and at most can be initialized with the values from the KUBECONFIG, but that host in no way can be equal to the new endpoint generated during the EKS creation. 

Since Terraform itself, prevents setting the dependence of provider resource(see [here](https://github.com/hashicorp/terraform/blob/51b0aee36cc2145f45f5b04051a01eb6eb7be8bf/internal/configs/provider.go#L84)) it is important to be able to utilize the option of 

_host                   = data.aws_eks_cluster.cluster.endpoint_

otherwise,  the provider is  not that different of adding all of the resources in a single yaml and playing with the  

_kubectl apply/delete -f <path_to_your_file>.yaml_

Could you please, add the support for that?

Thanks in advance!

**Comment by gavinbunney** [comment]
Hi @devprojectsme, this is already supported but may not be working in how you've setup your terraform.

In my projects, I have a top level module which includes an `eks` module that installs the AWS side of things. Then another module `kubernetes` which applies all the manifests. The way the `kubernetes` module provider is setup depends on variables for the eks cluster id, ca, endpoint etc which are fed as output from the `eks` module. This works in a single apply step and doesn't require separate runs like you've described. Perhaps you need to move the provider configuration from where it is defined right now?
