### ISSUE TITLE
Simplify name-based instead of index-based resource creation

### ISSUE THREAD

**Issue by nyurik** [gavinbunney/terraform-provider-kubectl#130]
When using multi-document YAML file(s), documentation suggests to use `count` and `element(...)` to access individual YAML blocks for each resource. I believe this is not very efficient in case the ordering of resources in the original YAML files change -- it may cause Terraform to destroy/regenerate resources even if there is no changes in them.

Instead, I believe a resource named approach (using `for_each`) is much safer and change-resilient, as I described in a [stackoverflow answer](https://stackoverflow.com/questions/54094575/how-to-run-kubectl-apply-commands-in-terraform/69512240#69512240):

```hcl
data "kubectl_file_documents" "myk8s" {
  content = file("./myk8s.yaml")
}

locals {
  # Create a map of { "kind--name" => raw_yaml }
  myk8s = { for value in [for v in data.kubectl_file_documents.myk8s.documents : [yamldecode(v), v]] :
    "${value.0["kind"]}--${value.0["metadata"]["name"]}" => value.1
  }
}

resource "kubectl_manifest" "myk8s" {
  for_each  = local.myk8s
  yaml_body = each.value
}
```

I think it would make sense to update documentation to recommend this method instead. Also, maybe add some new properties to the `data.kubectl_file_documents` so that it generates a map internally?

**Comment by gavinbunney** [comment]
Thanks @nyurik ! This indeed is becoming more of a pressing issue; I'm hitting it as well on the k8s clusters I'm maintaining, particularly when adding new manifests half-way into a document, throwing off the counts. Love that stackoverflow answer as well 👏 

Going to close this issue and track it under #72
