### ISSUE TITLE
kubectl_path_documents example is incorrect

### ISSUE THREAD

**Issue by ianhundere** [gavinbunney/terraform-provider-kubectl#135]
https://github.com/gavinbunney/terraform-provider-kubectl/blob/master/docs/data-sources/kubectl_path_documents.md

the example uses `kubectl_file_documents` instead of `kubectl_path_documents`.

**Comment by rverchere** [comment]
Hi, I think you should not use `toset()` and use `manifests`.

See https://github.com/gavinbunney/terraform-provider-kubectl/pull/140#issuecomment-1117142004
