### ISSUE TITLE
Defer initialisation of kubectl provider

### ISSUE THREAD

**Issue by ddelange** [gavinbunney/terraform-provider-kubectl#145]
### Scenario

Provision a kubernetes cluster - and apply some default configuration to it using `kubectl` - in the same terraform module

Example use-case: https://github.com/eddycharly/terraform-provider-kops/issues/438#issuecomment-998591993

### Problem

Supplying dynamic (computed during apply) values to a provider is currently not supported (ref https://github.com/hashicorp/terraform/issues/27934), AKA "provision a thing, then provision another thing inside the thing you just provisioned" ref https://github.com/hashicorp/terraform/issues/2430#issuecomment-800192314

### Workaround

- Avoid providing dynamic value to provider: pass a constant filename
- Lazy loading provider: e.g. providing `config_path` to the `helm` provider will only initialise when it's needed for a `helm_release` resource ref https://github.com/hashicorp/terraform/issues/2430#issuecomment-503419140
- Add appropriate `depends_on` to all its resources to ensure proper creation and destruction order

### Expected behaviour

kubectl provider only initialises once the first `kubectl_manifest` is applied (at this point in time, the kubernetes cluster is running and the kubeconfig file now exists/is updated on disk)

### Actual behaviour

`kubectl_manifest` resources will fail to apply on the first run:
```
failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
```

### Related issues

- https://github.com/hashicorp/terraform-provider-postgresql/issues/140

**Comment by stevehipwell** [comment]
@ddelange you need to use the [exec plugin](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins) authentication for Kubernetes or other kubernetes based providers such as `helm` or `kubectl`, AFAIK this is the only really reliable way to authenticate against Kubernetes.

**Comment by ddelange** [comment]
Thanks for the info, will close with that 💥
