### ISSUE TITLE
using datasource based on raw github content

### ISSUE THREAD

**Issue by chrisadkin** [gavinbunney/terraform-provider-kubectl#157]
Is I use raw github content, obviously something containing a YAML manifest as input to your provider for the YAML body, is there any reason why this would not work ?, I will test this for myself, but I was just wondering . . .

**Comment by gavinbunney** [comment]
The provider just needs the `yaml_body` string set - so you could fetch the raw github content via a http provider, then feed in the output of that into the kubectl_manifest resource
