### ISSUE TITLE
Applying several resources in same yaml file

### ISSUE THREAD

**Issue by shanedf** [gavinbunney/terraform-provider-kubectl#166]
Hey all,

Not sure if this is an issue, by design, or something I am missing in my configuration but I'm finding that when applying multiple resources in one yaml file (divided by '---' lines) that only the first resource is being processed.

Right now it's meaning that I have to download and split the yaml file manually and then terraform each piece separately... not so maintainable from an updates standpoint.

If anyone knows of any workarounds or tricks to overcome this I'd be thrilled 👯‍♂️

**Comment by gavinbunney** [comment]
You can use the provided data sources which will handle the splitting of those docs for you:
* `kubectl_file_documents` https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_file_documents
* `kubectl_path_documents` https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_path_documents
