### ISSUE TITLE
Terraform Cloud

### ISSUE THREAD

**Issue by ddiawara** [gavinbunney/terraform-provider-kubectl#17]
hello , i'm starting to use terraform cloud and actually i need to apply some manifests in my cluster but natevly i don't have a resource to do it. 
I like tools because it solve my problem very fast and very well but my question is : can this plugin work on Terraform Cloud. ???

**Comment by sebastianhutter** [comment]
Yes, it does. I am using it on terraform cloud.

To make it work on terraform cloud you need to download the linux_amd64 release and put it into a .terraform.d directory in the root of your git project

```
.terraform.d/plugins/linux_amd64/terraform-provider-kubectl
```
