### ISSUE TITLE
Add support for ARM-based devices (Macbook M1 Pro)

### ISSUE THREAD

**Issue by t1agob** [gavinbunney/terraform-provider-kubectl#173]
Hello,
I have been using this module for a while but since I started using a Macbook M1 Pro - ARM-based - I cannot use this module anymore due to the following error.

```
Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/gavinbunney/kubectl v1.10.0 does not have a package available for your current
│ platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms.
│ Other versions of this provider may have different platforms supported.
```

**Are there any plans to add support for ARM-based devices?**

Thanks in advance!

**Comment by alekc** [comment]
@t1agob until this is solved in this provider you can use 
```
required_providers {
    kubectl = {
      source = "alekc-forks/kubectl"
      version = "1.13.1-1"
    }
  }
```
(built from https://github.com/alekc-forks/terraform-provider-kubectl/releases/tag/v1.13.1-1)

**Comment by cferrera** [comment]
I'm facing the same issue upgrading to the latest `1.14.0` on M1 Pro - it works just fine until `1.13.2`

```
kubectl = {
  source = "gavinbunney/kubectl"
  version = "~> 1.14"
}
```
> Error: Failed to query available provider packages
> Could not retrieve the list of available versions for provider gavinbunney/kubectl: no available releases match
> the given constraints ~> 1.13.1, ~> 1.14

---

```
kubectl = {
  source = "gavinbunney/kubectl"
  version = "~> 1"
}
```
> \- Using previously-installed gavinbunney/kubectl v1.13.2
> Terraform has been successfully initialized!


Any ideas?

**Comment by alekc** [comment]
@cferrera did you run `terraform init -upgrade` or a simple `terraform init`?

**Comment by cferrera** [comment]
> @cferrera did you run `terraform init -upgrade` or a simple `terraform init`?

both logs reports were made with `terraform init -upgrade`

**Comment by alekc** [comment]
weird, just run it on macbook m1
```
➜ cat test.tf


terraform {
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
      #version = "1.14.0"
      version = "~> 1.14"
    }
  }
}

provider "kubectl" {
  # Configuration options
}

➜ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding gavinbunney/kubectl versions matching "~> 1.14"...
- Installing gavinbunney/kubectl v1.14.0...
- Installed gavinbunney/kubectl v1.14.0 (self-signed, key ID AD64217B5ADD572F)
```

are you sure that you do not have any module or similar asking for 1.13?
this row `no available releases match
the given constraints ~> 1.13.1, ~> 1.14` indicates that terraform was not able to satisfy your semver requirements (any patch version on 1.13 AND 1.14 or later)

**Comment by t1agob** [comment]
I was able to make it work on Macbook M1 by upgrading to version 1.14 as @alekc suggested. Thanks!

my current config: 

```terraform {
required_providers {
  kubectl = {
    source = "gavinbunney/kubectl"
      version = "~> 1.14"
    }
  }
}
```

Output:
```bash 
Initializing provider plugins...
- Finding gavinbunney/kubectl versions matching "~> 1.14"...
- Installing gavinbunney/kubectl v1.14.0...
- Installed gavinbunney/kubectl v1.14.0 (self-signed, key ID AD64217B5ADD572F)
```
