### ISSUE TITLE
live_manifest_incluster and yaml_incluster dont return YAML

### ISSUE THREAD

**Issue by techdragon** [gavinbunney/terraform-provider-kubectl#18]
These two attributes seem to return some kind of concatenated string version of an internal map representation, which looks like `fieldName:accessModes[0],fieldValue:ReadWriteOncefieldName:apiVersion,fieldValue:kubedb.com/v1alpha1fieldName:kind,fieldValue:Redis`<snip/>

They are either:
- broken and not doing what they were meant to do.
- documented wrong as the documentation says at least one of these should contain YAML explicitly and the other implicitly since you say it will contain the manifest (which is normally presented in YAML formal) 

From what I could make out in the code, you seem to handle them differently from the data you use later to generate the yaml_body representation.

**Comment by gavinbunney** [comment]
These fields are used for drift detection, however I've recently pushed a complete rewrite of that (in v1.7.0) to fix up some issues, notably around duplicate keys.
