### ISSUE TITLE
Create a datasource for URL documents

### ISSUE THREAD

**Issue by briantopping** [gavinbunney/terraform-provider-kubectl#26]
It would be useful to have a datasource that could pull documents from the internet. So instead of having 1,000 lines of YAML embedded in the `.tf`, just provide the URL to the YAML and voila!

**Comment by sebastianhutter** [comment]
Have a look at the "file" function of terraform.
it can't use an URL but you can put your kubernetes manifest into a separate file:

```
resource "kubectl_manifest" "mymanifest" {
  yaml_body = file("${path.module}/mymanifest.yaml")
}
```

**Comment by briantopping** [comment]
Hi @sebastianhutter thanks for the tip! I guess that helps keep everything idempotent if someone pastes a url from `master` branch. So I guess it depends on the audience and intent.

What I had envisioned was being able to set the desired version number in variables, interpolate the URL and load from there. It's a power tool, and sometimes power tools chop off fingers... 🤪

**Comment by sebastianhutter** [comment]
I like power tools ;-)

You can do that with terraform natively though. There is a "HTTP" datasource which downloads a file from an URL and which you can then feed into your resources:

https://www.terraform.io/docs/providers/http/data_source.html

```
data "http" "manifestfile" {
  url = "https://mycoolnawsomemanifesturl.com/${var.manifestversion}/manifest.yaml"
}

resource "kubectl_manifest" "mymanifest" {
  yaml_body = data.manifestfile.body
}
```
(untested though)

**Comment by smiletrl** [comment]
ln case there're multiple configs in the manifest.yaml, `"kubectl_path_documents"` might be necessary, since `"kubectl_manifest"` by default only runs [for the first config](https://github.com/gavinbunney/terraform-provider-kubectl/issues/52). `"null_resource"` can be used to download that yaml file firstly. Something like

```

resource "null_resource" "controller_rancher_installation" {

  provisioner "local-exec" {
    command = <<EOT
      echo "Downloading rancher config"
      curl -L https://some-url.yaml -o rancherconfig.yaml
    EOT
  }
}

data "kubectl_path_documents" "rancher_manifests" {
    // somehow pattern only supports search in local file directory, not from remote url.
    pattern = "./rancherconfig.yaml"
    depends_on = [null_resource.controller_rancher_installation]
}

```

**Comment by pduchnovsky** [comment]
> ln case there're multiple configs in the manifest.yaml, `"kubectl_path_documents"` might be necessary, since `"kubectl_manifest"` by default only runs [for the first config](https://github.com/gavinbunney/terraform-provider-kubectl/issues/52). `"null_resource"` can be used to download that yaml file firstly. Something like
> 
> ```
> 
> resource "null_resource" "controller_rancher_installation" {
> 
>   provisioner "local-exec" {
>     command = <<EOT
>       echo "Downloading rancher config"
>       curl -L https://some-url.yaml -o rancherconfig.yaml
>     EOT
>   }
> }
> 
> data "kubectl_path_documents" "rancher_manifests" {
>     // somehow pattern only supports search in local file directory, not from remote url.
>     pattern = "./rancherconfig.yaml"
>     depends_on = [null_resource.controller_rancher_installation]
> }
> ```

This wouldn't work then with kubectl_manifest which as per docu should be used with `count`
```
resource "kubectl_manifest" "test" {
    count     = length(data.kubectl_path_documents.manifests.documents)
    yaml_body = element(data.kubectl_path_documents.manifests.documents, count.index)
}
```
This is the error you'd get due to file not being available 'yet':
```
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

**Comment by smiletrl** [comment]
@pduchnovsky  as the error says, this error can be fixed by

```
% terraform apply -target=null_resource.controller_rancher_installation

% terraform apply -target=kubectl_path_documents.rancher_manifests

// Test with this command, or simply run terraform apply. It should work well with `terraform`
% terraform apply -target=kubectl_manifest.test
```

See more at https://www.hashicorp.com/blog/resource-targeting-in-terraform.

**Comment by pduchnovsky** [comment]
> @pduchnovsky as the error says, this error can be fixed by
> 
> ```
> % terraform apply -target=null_resource.controller_rancher_installation
> 
> % terraform apply -target=kubectl_path_documents.rancher_manifests
> 
> // Test with this command, or simply run terraform apply. It should work well with `terraform apply` after the dependent file resource has been applied before.
> % terraform apply -target=kubectl_manifest.test
> ```
> 
> See more at https://www.hashicorp.com/blog/resource-targeting-in-terraform.

If you use terraform cloud as we do for fully automated deployment this is not possible though.

**Comment by smiletrl** [comment]
ah, not sure how your deployment process works. In my imagination, maybe run this command in `terraform apply -target=kubectl_path_documents.rancher_manifests` before `terraform apply` in the jenkins phase or circleci step?

**Comment by pduchnovsky** [comment]
> ah, not sure how your deployment process works. In my imagination, maybe run this command in `terraform apply -target=kubectl_path_documents.rancher_manifests` before `terraform apply` in the jenkins phase or circleci step?

terraform cloud performs changes on environment automatically based on commits to monitored repository, also they do not allow terraform apply on remote backend therefore this workaround wouldn't be viable.

**Comment by tommyjcarpenter** [comment]
@sebastianhutter  you need `data.http.manifestfile.body`

**Comment by luisdavim** [comment]
I tried using the `kubectl_file_documents` data source together with the `http` data source but keep running into https://github.com/gavinbunney/terraform-provider-kubectl/issues/61#issuecomment-1015642912

**Comment by HeWhoWas** [comment]
I too am seeing a similar issue - in my case, the YAML documents are generated by Rancher on a per-cluster basis, so using static ones isn't an option as there is still a dependency on the `http` data source for, at the very least, a unique token.

**Comment by panaut0lordv** [comment]
With the latest http provider use:
`  content = data.http.metrics_server_raw.response_body`
instead of
`  content = data.http.metrics_server_raw.body`

**Comment by akhilrajmailbox** [comment]
###### Providers ######
terraform {
  required_version = ">=1.8"
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.14.0"
    }
  }
}

provider "kubectl" {
    config_path    = "~/.kube/config"
}

###### Resources ######
data "http" "manifestfile" {
  url = "https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/crds/crds.yaml"
}

data "kubectl_file_documents" "alb_crds" {
  content = data.http.manifestfile.response_body
}

resource "kubectl_manifest" "alb_crds" {
  for_each  = data. kubectl_file_documents.alb_crds.manifests
  yaml_body = each.value
}
