### ISSUE TITLE
Failed to  retrieve authentication checksums for provider

### ISSUE THREAD

**Issue by davejhahn** [gavinbunney/terraform-provider-kubectl#264]
We've been using this provider for > 1 year and all of the sudden we started seeing the following during the init:

 Error while installing gavinbunney/kubectl v1.14.0: could not query
 provider registry for registry.terraform.io/gavinbunney/kubectl: failed to
 retrieve authentication checksums for provider: the request failed after 2
 attempts, please try again later: Get
 "https://objects.githubusercontent.com/github-production-release-asset-2e65be/XXXXX":
 
Full URL obfuscated w/XXXXX

The URL that is displayed, if visited, returns a 401 (although not sure if it would ever work directly).

Not occurring locally but happening on our build agents to add another twist.

**Comment by MikeBlomm** [comment]
Same issue, also only with automated pipelines (Github Actions). Only solution was to disable the provider..

**Comment by davejhahn** [comment]
This happens periodically, we've learned to live with it.

**Comment by davidpasqua-asml** [comment]
really 2 years later and this still happening

**Comment by bats64mgutsi** [comment]
2026. Still happening.
