### ISSUE TITLE
gavenbunny kubectl provider is down.

### ISSUE THREAD

**Issue by pranavnateri** [gavinbunney/terraform-provider-kubectl#272]
Error while installing gavinbunney/kubectl v1.14.0: could not query provider registry for registry.terraform.io/gavinbunney/kubectl: failed to retrieve authentication checksums for provider: the request
│ failed after 2 attempts, please try again later: 503 Service Unavailable returned from objects.githubusercontent.com

gavenbunny kubectl provider is down. pls bring it up asap.. our pipelines are failing

**Comment by Antvirf** [comment]
Try running your flow again, this is likely temporary / github issue

**Comment by komapa** [comment]
It is right in the error `503 Service Unavailable returned from objects.githubusercontent.com`

**Comment by ArronaxKP** [comment]
That was likely a GitHub issue rather than provider specific. 

You may want to swap to consider swapping to Alekc version going forward as that has had some quite important updates https://github.com/alekc/terraform-provider-kubectl
