### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by jyothi-balla** [gavinbunney/terraform-provider-kubectl#279]
kubectl_manifest gives error when we update the yaml file during terraform apply

`When expanding the plan for
 module.aks_base_config.kubectl_manifest.store_azure_info[0] to include new
 values learned so far during apply, provider
 "registry.terraform.io/gavinbunney/kubectl" produced an invalid new value
 for .yaml_body_parsed: was cty.StringVal(....
This is a bug in the provider, which should be reported in the provider's
own issue tracker.`

Using 
`data "kubectl_file_documents" .. `
and 
<pre>resource "kubectl_manifest" "store_azure_info" {
  count      = length(split("\n---\n", file("${path.module}/manifests/ </pre>

Kubectl provider version - 1.14.0
Terraform v1.3.5

**Comment by alekc** [comment]
A known bug due to the lack of development on this provider. Try to use this fork
```
terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
      version = "2.0.4"
    }
  }
}
```

**Comment by omerfsen** [comment]
Thank you @alekc  It seems it is not maintained since last 2 years. I will test yours to see it is %100 compatible.
