### ISSUE TITLE
Datasource kubectl_path_documents documentation typo

### ISSUE THREAD

**Issue by DevopsMercenary** [gavinbunney/terraform-provider-kubectl#286]
At the Example Usage on the documentation for kubectl_path_documents

https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_path_documents

The first example, for the `for_each` uses documents.  I'm pretty sure this should be `manifests`

resource "kubectl_manifest" "test" {
    for_each  = toset(data.kubectl_path_documents.docs.manifests)
    yaml_body = each.value
}

**Comment by gavinbunney** [comment]
Thanks for the report. Has been fixed in #299
