### ISSUE TITLE
<name> failed to fetch resource from kubernetes: the server could not find the requested resource

### ISSUE THREAD

**Issue by abhiverma111** [gavinbunney/terraform-provider-kubectl#287]
Post EKS 1.27 upgradation getting the below error while creating the resource "kubectl_manifest" "constraint_template" using terraform.

It works fine with EKS 1.26

![image](https://github.com/gavinbunney/terraform-provider-kubectl/assets/155755871/d86fd20e-da95-4dd5-bdeb-528443c66f66)

**Comment by alekc** [comment]
As mentioned in https://github.com/gavinbunney/terraform-provider-kubectl/issues/270, this is a pretty much abandoned project. The fix has been rolled out in the fork
```
terraform {
  required_version = ">= 0.13"

  required_providers {
    kubectl = {
      source  = "alekc/kubectl"
      version = ">= 2.0.2"
    }
  }
```
