### ISSUE TITLE
Submit the public key for Provider signing to OpenTofu

### ISSUE THREAD

**Issue by mpepping** [gavinbunney/terraform-provider-kubectl#294]
Using the gavinbunney/kubectl provider with OpenTofu shows a warning on Signature validation:

`Installed gavinbunney/kubectl v1.14.0. Signature validation was skipped due to the registry not containing GPG keys for this provider`

There's a "Submit new Provider Signing Key" issue template on the OpenTofu registry project to make submitting GPG public keys easy: 

https://github.com/opentofu/registry/issues/new/choose

**Would you please take a moment to submit the public signing key to the OpenTofu project, so that tofu users can install the gavinbunney/kubectl provider without any warnings?** 

An example of a submitted issue can be [found here](https://github.com/opentofu/registry/issues/206).

**Comment by mpepping** [comment]
@gavinbunney, can you look into this? Low effort, but actually fixing this comes down to you.

**Comment by chris-mcclure-array** [comment]
I also would like you to look into this. It caused a whole mess of problems with our setup.

**Comment by venkateshan62** [comment]
@gavinbunney  We also fixing the key issue issue. Can you please help on this issue

**Comment by alekc** [comment]
Just fiy, this provider is long abandoned and causing issues on newer versions of kubernetes. There is a fork I am maintaining (with some new features) at https://registry.terraform.io/providers/alekc/kubectl/latest/docs

**Comment by gavinbunney** [comment]
Done in https://github.com/opentofu/registry/pull/1327

**Comment by TheKangaroo** [comment]
For me, this completely broke the deployment. Previously, I had a warning about a missing signing key. Since today, I receive an error indicating that the signing key is not valid, causing my tofu run to fail.
