### ISSUE TITLE
Failed to configure: specifying a root certificates file with the insecure flag is not allowed

### ISSUE THREAD

**Issue by ruby232** [gavinbunney/terraform-provider-kubectl#33]
I'm try use this provider, but alway launching the error:

```
Error: Failed to configure: specifying a root certificates file with the insecure flag is not allowed

  on _provider.tf line 5, in provider "kubectl":
   5: provider "kubectl" {
```

Im use:
**terraform-provider-kubectl:** version 1.6.2
**Kubernetes** cluster created by me with **k3s** and management with **Rancher2**

kubeconfig.yml
```yml
apiVersion: v1
kind: Config
clusters:
- name: "mycluster"
  cluster:
    server: "https://rancher.my.com/k8s/clusters/a-3gd5r"
    certificate-authority-data: "cerificate here"

users:
- name: "mycluster"
  user:
    token: "kubeconfig-user-bxdpx:mytoken"

contexts:
- name: "mycluster"
  context:
    user: "mycluster"
    cluster: "mycluster"

current-context: "mycluster"
```
 
_provider.tf
```tf
provider "kubectl" {
  config_path = "kubeconfig.yml"
}
```

When you run
```shell
terraform apply
```

throws the error
```
Error: Failed to configure: specifying a root certificates file with the insecure flag is not allowed

  on _provider.tf line 5, in provider "kubectl":
   5: provider "kubectl" {

```
**Note:** Same configuration work fine with kubernetes provider.

**Comment by gavinbunney** [comment]
Hi @ruby232 , your configuration looks ok as it's not explicitly trying to use an insecure mode. You don't happen to have `KUBE_INSECURE` environment variable set? As that would force it to attempt to use an insecure mode even though you are using TLS & provided a CA. Let me know if it still isn't working.
