### ISSUE TITLE
Support Terraform 0.13

### ISSUE THREAD

**Issue by derkoe** [gavinbunney/terraform-provider-kubectl#34]
Just tried the provider with [0.13](https://github.com/hashicorp/terraform/releases/tag/v0.13.0) and Terraform does not find the plugin. Everything works with Terraform v0.12.29

**Comment by galkin** [comment]
@derkoe, could you add?
```
terraform {
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.6.2"
    }
  }
}
```
 It helps for me

**Comment by derkoe** [comment]
No doesn't seem to work:
```
❯ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/azurerm v2.22.0
- Using previously-installed gavinbunney/kubectl v1.6.2
- Using previously-installed -/azurerm v2.22.0
- Finding latest version of -/kubectl...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/kubectl:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/kubectl
```

Same command with same setup/files works with `0.12.29`.

I'm running on Windows 10.

**Comment by galkin** [comment]
I guess you use modules at your project. One of the module requires `-/kubectl` instead of `gavinbunney/kubectl`

You need fix the module by adding `required_providers ...`

**Comment by derkoe** [comment]
OK - got it working now. Had to remove my tfstate files then it worked.
