### ISSUE TITLE
Provider configuration does not work as expected

### ISSUE THREAD

**Issue by codeheap** [gavinbunney/terraform-provider-kubectl#35]
Hello,

I'm trying to use the provider for injecting some yaml into Azure AKS. I configure it like this:

provider "kubectl" {
  config_context_cluster = "crt-${var.domain_name}-${var.stage_name}-aks"
}

the same configuration is working for the kubernetes provider. But this provider always stays on "localhost":
> create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp 127.0.0.1:80: connect: connection refused

Which cannot work, because the whole deployment / terraform is done in a separate pod inside the aks. It's difficult to explain but we have a massive automated infrastructure on Azure for our Application Development etc. So I cannot use "static" configuration. It's totally dynamic and I don't have access to e.g. the certificates. 

As mentioned the configuration is working for the kubernetes provider.

Any hints or advises ?

provider version 1.6.2
terraform version 0.12.20

**Comment by gavinbunney** [comment]
Hi @codeheap ! This is an interesting one. The kubectl provider has the same logic around loading the `config_context_cluster` as the kubernetes provider does. Can you provide any more details around those `var` variable? Are they set from other modules in the same terraform project or manually set?

It's also worthwhile running with `TF_LOG=DEBUG` mode turned on, in which case you should see:

```
[DEBUG] Using custom current context:
or
[DEBUG] Using overidden context:
```

**Comment by gavinbunney** [comment]
Closing for now - v1.8.0 has upgraded the kubernetes libs to latest v1.17.12 version - let me know if you run into other issues

**Comment by codeheap** [comment]
Hello @gavinbunney 

Thanks for your comment. I was very busy the last two weeks.

I think now it is not a bug in the provider. I belevie now this happens because of the configuration of our AKS Nodes.

We recently updated to terraform 0.13. After that update the kubernetes provider did the same thing. Locally on my machine the config context was set correctly. But  on the AKS clusters it could't resolve the corresponding IP of the cluster and tried always to "phone" on 127.0.0.1.
So we made some experiments and logged out a lot of stuff. Also all possible ENV Variables. Especially we found out that KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT was set on the nodes. Which I don't do locally. 
We changed the provider configuration to:
provider "kubernetes" {
  load_config_file = "false"
}
and then it was working!

So I think it's more our configuration. I don't understand why the other team who makes the infrastructure part came to this idea. Beacuse I was assuming there is a .kubeconfig file on the nodes containing the config. But it's not. 

Hope this can help also other people when they they have similar issues. Check the configuration on your cluster nodes, because this can lead into some strange behaviours.

**Comment by MoskitoHero** [comment]
In case anyone comes across this thread, I had the same issue today and solved it by adding `load_config_file = "false"`, not to the `kubernetes` provider, but to the `kubectl` provider.

```terraform
provider "kubectl" {
  # ...
  load_config_file       = "false"
}
```

**Comment by brandonros** [comment]
```hcl
provider "kubernetes" {
  host                   = 
  username               = azurerm_kubernetes_cluster.redacted.kube_config.0.username
  password               = azurerm_kubernetes_cluster.redacted.kube_config.0.password
  client_certificate     = base64decode(azurerm_kubernetes_cluster.redacted.kube_config.0.client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.redacted.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.redacted.kube_config.0.cluster_ca_certificate)
}
```

what does token correspond to for AKS/azure?

**Comment by suniilsync** [comment]
Hi, 

I ran into the same issues,   when run the deploy I get the below error,

`│ Error: failed to create kubernetes rest client for read of resource: Get "[http://localhost/api?timeout=32s"](http://localhost/api?timeout=32s%22): dial tcp [::1]:80: connect: connection refused`
 
As per the above suggestion, when I add `load_config_file       = false`, I get the below error

`Error: kube-system/coredns-custom failed to create kubernetes rest client for update of resource: resource [v1/ConfigMap] isn't valid for cluster, check the APIVersion and Kind fields are valid
`

any idea what could be the issues?

**Comment by suniilsync** [comment]
> 

Hello Thomas Hasler, 

Since you had mentioned this solved for you, could you please provide me the more info on it?

here we are doing the same as you, we are running terraform on the POD (which is in a different cluster), against the aks on another cluster.

**Comment by suniilsync** [comment]
> 

I did the following to get the AKS token, 

1. We need to create the service account for AKS
2. Fetch the token


###  We need the Kubernetes provider to create a service account
```
provider "kubernetes" {
    host                   = azurerm_kubernetes_cluster.this.kube_admin_config.0.host
    username               = azurerm_kubernetes_cluster.this.kube_admin_config.0.username
    password               = azurerm_kubernetes_cluster.this.kube_admin_config.0.password
    client_certificate     = base64decode(azurerm_kubernetes_cluster.this.kube_admin_config.0.client_certificate)
    client_key             = base64decode(azurerm_kubernetes_cluster.this.kube_admin_config.0.client_key)
    cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.this.kube_admin_config.0.cluster_ca_certificate)
}

```
### Create ake service account 
```
resource "kubernetes_service_account" "terraform" {
    automount_service_account_token = true
    metadata {
        name = "terraform"
    }
    depends_on = [azurerm_kubernetes_cluster.this]
}
```
### Create a role 
```
resource "kubernetes_cluster_role" "terraform" {
    metadata {
        name = "terraform"
    }
    rule {
        api_groups = [""]
        resources  = ["configmaps"]
        verbs      = ["get", "list", "update", "create", "patch"]
    }
}
```
### Assign role
```
resource "kubernetes_cluster_role_binding" "terraform" {
    
    metadata {
        name = "terraform"
    }
    role_ref {
        api_group = "rbac.authorization.k8s.io"
        kind      = "ClusterRole"
        name      = kubernetes_cluster_role.terraform.metadata[0].name
    }
    subject {
        kind      = "ServiceAccount"
        name      = kubernetes_service_account.terraform.metadata[0].name
    }
}
```


### Get data
```
data "kubernetes_secret" "terraform" {
    metadata {
        name = "${kubernetes_service_account.terraform.default_secret_name}"
    }
}

```
then 


```

provider "kubectl" {
     load_config_file             = false
     host                             = "${data.azurerm_kubernetes_cluster.this.kube_config.0.host}"
     cluster_ca_certificate     = lookup(data.kubernetes_secret.terraform.data, "ca.crt")
     token                             = lookup(data.kubernetes_secret.terraform.data, "token")
 }

**Comment by k0eff** [comment]
For anyone who has stumbled upon this topic here - using gavinbunney / terraform-provider-kubectl with Azure - you need to provide the following variables:


`
provider "kubectl" {
  load_config_file = false
  host = azurerm_kubernetes_cluster.REDACTED.kube_config.0.host
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.REDACTED.kube_config.0.cluster_ca_certificate)
  token = yamldecode(azurerm_kubernetes_cluster.REDACTED.kube_config_raw).users[0].user.token
}
`

If you receive an error like this:
`Error: nginx-deployment failed to create kubernetes rest client for update of resource: Get "https://REDACTED.hcp.northeurope.azmk8s.io:443/api?timeout=32s": x509: certificate signed by unknown authority`

then make sure you've used 
`
base64decode()
`
in order to decode the cluster certificate authority

Hope I've helped someone!
