### ISSUE TITLE
Releases have changed from binaries to zipped binaries

### ISSUE THREAD

**Issue by rjhenry** [gavinbunney/terraform-provider-kubectl#36]
With the change from binaries to zipped binaries, the automated pipelines built which use the latest release break. In addition, the [usage guide's manual install instructions](https://gavinbunney.github.io/terraform-provider-kubectl/docs/provider.html#install-manually) say to remove the arch detail, but don't mention unzipping.

While most people will imply it, documentation should probably be kept up to date.

**Comment by gavinbunney** [comment]
Docs have been updated - thanks and good point!
