### ISSUE TITLE
Terraform 13 Error: Invalid provider registry host

### ISSUE THREAD

**Issue by jknott-terraform** [gavinbunney/terraform-provider-kubectl#39]
Error: Invalid provider registry host

The given source address "github.com/gavinbunney/kubectl" specifies a GitHub
repository rather than a Terraform provider. Refer to the documentation of the
provider to find the correct source address to use.

In terraform block

    kubectl    = {
       # https://github.com/gavinbunney/terraform-provider-kubectl/releases
       # see README.md for updates (requires deployment into terraform.d folder
       source  = "github.com/gavinbunney/kubectl"
       #version = "1.5.0"
     }

**Comment by tinder-tder** [comment]
For tf13 setup your versions.tf like this instead:
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.6.2"
    }
  }
}
```

**Comment by jknott-terraform** [comment]
Thank You!!!

**Comment by jknott-terraform** [comment]
Error: Failed to install provider

Error while installing hashicorp/kubectl: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kubectl

**Comment by briangordonmills** [comment]
I'm getting a similar error as jknott-terraform.  I'm using terraform cloud...if that changes things at all.
----------
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/kubectl:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/kubectl

**Comment by jknott-terraform** [comment]
@briangordonmills I was able to get it to work. Here is what I did. Change your home user mine is avenger.
```export TERRAFORM_PROVIDER_KUBECTL_VERSION="1.6.2"
    mkdir -p /home/avenger/.terraform.d/plugins/linux_amd64 \
    && curl -sS -L -o /home/avenger/.terraform.d/plugins/linux_amd64/terraform-provider-kubectl_v${TERRAFORM_PROVIDER_KUBECTL_VERSION} https://github.com/gavinbunney/terraform-provider-kubectl/releases/download/v${TERRAFORM_PROVIDER_KUBECTL_VERSION}/terraform-provider-kubectl-linux-amd64 \
    && chmod +x /home/avenger/.terraform.d/plugins/linux_amd64/terraform-provider-kubectl_v${TERRAFORM_PROVIDER_KUBECTL_VERSION} \
    && mkdir -p /home/avenger/.terraform.d/plugins/github.com/gavinbunney/kubectl \
    && bsdtar -a -C /home/avenger/.terraform.d/plugins/linux_amd64 -cf /home/avenger/.terraform.d/plugins/github.com/gavinbunney/kubectl/terraform-provider-kubectl_${TERRAFORM_PROVIDER_KUBECTL_VERSION}_linux_amd64.zip terraform-provider-kubectl_v${TERRAFORM_PROVIDER_KUBECTL_VERSION} \
    && echo "{\"versions\": {\"${TERRAFORM_PROVIDER_KUBECTL_VERSION}\": {}}}" > /home/avenger/.terraform.d/plugins/github.com/gavinbunney/kubectl/index.json \
    && echo "{\"archives\": {\"linux_amd64\": {\"url\": \"terraform-provider-kubectl_${TERRAFORM_PROVIDER_KUBECTL_VERSION}_linux_amd64.zip\"}}}" > /home/avenger/.terraform.d/plugins/github.com/gavinbunney/kubectl/${TERRAFORM_PROVIDER_KUBECTL_VERSION}.json
```

**Comment by briangordonmills** [comment]
@jknott-terraform I attempted to do this approach to configuration.  Seemed to look like it should work.  Unfortunately, I'm hitting trouble in Terraform Cloud.  I did notice that @gavinbunney has a registered Provider in Terraform Cloud.  I'm attempting to use that now...I'll update on what happens.

**Comment by y6vmeq** [comment]
How solve this problem?
My error
![изображение](https://user-images.githubusercontent.com/46869350/91975582-488e9500-ed28-11ea-9713-609c6a583b7a.png)

How i declare provider.
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
      version = "1.6.2"
    }
  }
}
```

**Comment by atlan14** [comment]
@jknott-terraform unfortunately, this did not resolve my issue. I still face the same problem:

```
Error: Failed to install provider

Error while installing hashicorp/kubectl: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kubectl
```

**Comment by briangordonmills** [comment]
I've been talking with a Hashicorp engineer.  Hopefully, I'll have some feedback in a day or two.  I'll update this when I hear back.  I've tried with 13.0, 13.1, and 13.2.  All that *should* be necessary is to declare the provider as shown by @y6vmeq above.

**Comment by kam1kaze** [comment]
I've faced with the same issue. I've made a research and found: declare block should be placed to each module where kubectl resource is used. You can easily find what module contains kubectl resources by `terraform providers`.

Example:
```
❯ terraform providers

Providers required by configuration:
.

├── module.gke_main_v3
│   ├── provider[registry.terraform.io/gavinbunney/kubectl] 1.6.2.  <<< OK!
│   ├── provider[registry.terraform.io/hashicorp/kubernetes] 1.13.1
│   ├── provider[registry.terraform.io/terraform-providers/cloudflare]
│   ├── provider[registry.terraform.io/hashicorp/external]
│   ├── provider[registry.terraform.io/hashicorp/google]
│   ├── provider[registry.terraform.io/hashicorp/google-beta]
│   ├── provider[registry.terraform.io/hashicorp/random]
│   ├── provider[registry.terraform.io/hashicorp/helm] 1.3.0
│   ├── module.cert-manager
│       ├── provider[registry.terraform.io/hashicorp/kubectl]   <<< FAIL!
│       ├── provider[registry.terraform.io/hashicorp/helm]
│       ├── provider[registry.terraform.io/hashicorp/kubernetes]
│       └── provider[registry.terraform.io/hashicorp/external]

```

So we have to find `module.cert-manager` source code and the following block to it:

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
      version = "1.6.2"
    }
  }
}
```

**Comment by atlan14** [comment]
I have also tried that, but I am facing the problem that my module includes a depends_on configuration on module level. Then it is not allowed to have a provider definition within the module any more.

For this case I have also tried to specifically define the providers for the module, but it still does not work...

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.6.2"
    }
  }
} 

provider kubectl {
    alias = "gavinbunney"
    #my config...
}

module my-module {
    #this hinders provider definitions within a module
    depends_on = [module.my-other-module]
    source = "./my-module"

    providers = {
        kubectl = kubectl.gavinbunney
    }
}
```

still my error:

```
Initializing provider plugins...
- Using previously-installed gavinbunney/kubectl v1.6.2

Error: Failed to install provider

Error while installing hashicorp/kubectl: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kubectl
```

**Comment by bizmate** [comment]
Not sure if you are all still experiencing this but it is working for me on the latest terraform v0.13.2

**Comment by martin-schaefer** [comment]
For me this does not work. I have the following providers declared. Using Terraform v0.13.3.

```
terraform {
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
      version = "1.7.1"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = ">=1.13.2"
    }
  }
  required_version = ">= 0.13"
}

```
Then doing `terraform init` on a fresh workspace results in:

```
Initializing provider plugins...
- Finding gavinbunney/kubectl versions matching "1.7.1"...
- Finding hashicorp/kubernetes versions matching ">= 1.13.2"...
- Finding latest version of hashicorp/kubectl...
- Installing gavinbunney/kubectl v1.7.1...
- Installed gavinbunney/kubectl v1.7.1 (self-signed, key ID AD64217B5ADD572F)
- Installing hashicorp/kubernetes v1.13.2...
- Installed hashicorp/kubernetes v1.13.2 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/kubectl: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kubectl
```

**Comment by gavinbunney** [comment]
As most of this is general issues with Terraform v0.13, going to close it out. As @kam1kaze mentioned, you need to specify the provider block in each module as it doesn't seem to inherit it. Let me know if there is something provider specific around TFv0.13 here, otherwise let's hope that Terraform makes this a bit easier going forward!

**Comment by MMN3003** [comment]
## Download providers
To download the proper versions of the `hashicorp/helm` and `hashicorp/kubernetes` providers, follow these steps:

- Visit the following link to access the releases for the `terraform-provider-helm`: [Terraform-Provider-Helm Versions | HashiCorp Releases](https://releases.hashicorp.com/terraform-provider-helm/).
- From the list of versions provided on the page, choose the version that you require for `hashicorp/helm`.
- Download the corresponding zip file for the selected version.

- Visit the following link to access the releases for the `terraform-provider-kubernetes`: [Terraform-Provider-Kubernetes Versions | HashiCorp Releases](https://releases.hashicorp.com/terraform-provider-kubernetes/).
- From the list of versions provided on the page, choose the version that you require for `hashicorp/kubernetes`.
- Download the corresponding zip file for the selected version.

## Move providers to the plugin directory
Once you have downloaded the providers, follow these steps to move them to the appropriate plugin directories:

- If the directories don't already exist, create them:
  - For `hashicorp/helm`, create the directory: `$HOME/.terraform.d/plugins/registry.terraform.io/hashicorp/helm`
  - For `hashicorp/kubernetes`, create the directory: `$HOME/.terraform.d/plugins/registry.terraform.io/hashicorp/kubernetes`

- Move the downloaded zip files to their respective directories.

## Initialize and install
To initialize and install the providers, proceed with the following steps:

- Create a file named `provider.tf` and add the following content:

```tf
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.26.0" # Replace with the version you downloaded earlier for hashicorp/kubernetes
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.12.1" # Replace with the version you downloaded earlier for hashicorp/helm
    }
  }
}
```

- Run the command `TF_LOG=trace terraform init` to initialize and install the providers.
- The `TF_LOG=trace` flag enables more detailed logging, providing additional information during the initialization process.
