### ISSUE TITLE
Feature request: kustomize support

### ISSUE THREAD

**Issue by lukasmrtvy** [gavinbunney/terraform-provider-kubectl#4]
Would be great to have kustomize support https://github.com/kubernetes-sigs/kustomize
Its already implemented in kubectl client and I think its worth to have it.

Handle:
- template $overlay_file
- kubectl kustomize base > $file
- kubectl apply -f $file
or
- template $overlay_file
- kubectl build base | kubectl apply -f
or
- template $overlay_file
- kubectl apply -k base

**Comment by gavinbunney** [comment]
Hi @lukasmrtvy - neat idea!

I haven't used kustomize a lot, but thinking out loud, could you achieve a similar feature using built-in terraform templates? The `kubectl_manifest` takes a `yaml_body` which can be any string, so you could then use an inbuilt terraform template to render out the file changes you wanted?

Is there another feature set of kustomize that would be useful? Apart from being able to run kustomized templates that is 🍡

**Comment by lukasmrtvy** [comment]
@gavinbunney Hello,
Yes, its doable with external datasource, even with kustomize binary itself ( takes DIR asi input a produce RAW manifest )
