### ISSUE TITLE
Add namespace as argument of kubectl_manifest resource

### ISSUE THREAD

**Issue by jakubpawlowski** [gavinbunney/terraform-provider-kubectl#43]
At the moment namespace can only be specified in yaml files.
However if namespace could be provided as an argument, it would make yaml files more portable. For this reason most yaml files don't specify the namespace which is injected using "--namespace" option to kubectl.

**Comment by gavinbunney** [comment]
Released in v1.9.0

**Comment by toabi** [comment]
This also solved https://github.com/gavinbunney/terraform-provider-kubectl/issues/23 - thanks.
