### ISSUE TITLE
Use a configuration file instead of manually specifying authentication values

### ISSUE THREAD

**Issue by bizmate** [gavinbunney/terraform-provider-kubectl#44]
Is it possible to use an arbitrary (not loaded under a fixed location) file for authentication as it can be done with the helm provider?

https://registry.terraform.io/providers/hashicorp/helm/latest/docs#authentication

```
provider "helm" {
  kubernetes {
    config_path = "../infra/kube_config_cluster.yml"
  }
}
```

**Comment by gavinbunney** [comment]
Hi @bizmate , yes this is already possible via the `config_path` option. By default it uses the `KUBECONFIG` environment variable, but you can specify a path just like your example:

```hcl
provider "kubectl" {
  config_path = "../infra/kube_config_cluster.yml"
}
```
