### ISSUE TITLE
updating CRDs hangs for ever

### ISSUE THREAD

**Issue by yanndegat** [gavinbunney/terraform-provider-kubectl#46]
due to 

- https://cert-manager.io/docs/installation/upgrading/upgrading-0.15-0.16/#issue-with-older-versions-of-kubectl
- https://github.com/kubernetes/kubernetes/issues/91615

updating some CRDs (eg: certmanager crds) hangs forever with the provider

lib kubectl should be updated to fix this issue.
probably bumping go.mod to `https://pkg.go.dev/mod/k8s.io/kubectl@v0.17.12` shoud do the trick

**Comment by gavinbunney** [comment]
Updated to v0.17.12 Hope that fixes the issue 🕺 Released in v1.8.0

**Comment by ameet-nandihal** [comment]
Hey @gavinbunney  i also faced same issue with v1.9.1 version. do i need to use v1.8.0 only?
