### ISSUE TITLE
can't process large file

### ISSUE THREAD

**Issue by day2up2** [gavinbunney/terraform-provider-kubectl#5]
Hi, Gavin,

We just found that this provider can't process large file since the scanner use the default tokensize (64*1024). I want to make a PR for this issue. However, looks like I can't push my code to a branch. Is there a way to do so?

thanks,

Yilong from Guidewire

**Comment by gavinbunney** [comment]
Hi @day2up2 - the normal github contribution process involves creating a fork against your account, pushing there, then creating a PR back to this repo.

https://gist.github.com/Chaser324/ce0505fbed06b947d962
