### ISSUE TITLE
[Feature Request] Option for ignore errors or/and retries in kubectl_manifest resource

### ISSUE THREAD

**Issue by feliperfmarques** [gavinbunney/terraform-provider-kubectl#51]
Hi,

firstly I would like to thanks and congrats the creator for this great terraform provider. In fact, currently I consider this the best way for managing kubernetes manifests with Terraform.

But, today I face a issue for install istio using manifests generated by istioctl tool, according [istio documentation](https://istio.io/latest/docs/setup/install/istioctl/): 

```
The output from manifest generate can also be used to install Istio using kubectl apply or equivalent. However, these alternative installation methods may not apply the resources with the same sequencing of dependencies as istioctl install and are not tested in an Istio release.
```

These generated manifests necessarily aren't in correct sequence, for this reason errors can happens when apply it using kubectl. So, would be very useful a option for ignore errors or retries in kubectl_manifest resource.

I can to contribute with a PR, but I need a little help for that :)

**Comment by QwertV2** [comment]
I have the same exact issue

**Comment by gavinbunney** [comment]
Hi @feliperfmarques, you can increase the inbuilt number of retries via the `apply_retry_count` flag:

```
provider "kubectl" {
  apply_retry_count = 15
}
```

The alternative (which I do for some large projects), is to split out things like CRDs into their own files, apply those, then apply the other resources. e.g.

```
data "kubectl_path_documents" "crd" {
  pattern = "./01-*.yaml"
}

resource "kubectl_manifest" "crd" {
  wait = true
  count     = length(data.kubectl_path_documents.crd.documents)
  yaml_body = element(data.kubectl_path_documents.crd.documents, count.index)
}

data "kubectl_path_documents" "deployment" {
  pattern = "./02-*.yaml"
}

resource "kubectl_manifest" "deployment" {
  wait = true
  count     = length(data.kubectl_path_documents.deployment.documents)
  yaml_body = element(data.kubectl_path_documents.deployment.documents, count.index)
  depends_on = [kubectl_manifest.crd]
}
```
