### ISSUE TITLE
terraform apply error "o work with kubectl_manifest.alb_ingress_controller its original provider configuration at provider["registry.terraform.io/gavinbunney/kubectl"] is required, but it has been remove"

### ISSUE THREAD

**Issue by caoheyang** [gavinbunney/terraform-provider-kubectl#53]
When I commented out the resource I created through 
"terraform-provider-kubectl", and re-use "terraform apply" command,it prompted: 

Error: Provider configuration not present

To work with kubectl_manifest.alb_ingress_controller its original provider
configuration at provider["registry.terraform.io/gavinbunney/kubectl"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
kubectl_manifest.alb_ingress_controller, after which you can remove the
provider configuration again.

Could you give me some kindly help please? Thanks.
![image](https://user-images.githubusercontent.com/9813751/96682539-8b293100-13ab-11eb-9b0f-bad2c1306a37.png)

**Comment by gavinbunney** [comment]
This is from base terraform. Likely you have removed the `provider` definition or it can't reference it. Lots of help and solutions in the main terraform repo: https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen++This+occurs+when+a+provider+configuration
