### ISSUE TITLE
terraform in trying to find hashicorp/kubectl when used in module 

### ISSUE THREAD

**Issue by aaadipop** [gavinbunney/terraform-provider-kubectl#54]
Hello,

I have a strange behaviour when I try to add a module containing one resource from gavinbunney/kubectl into a module

When I have the `resource "kubectl_manifest"` in main.tf everything works good but when I try to add a module with that resource terraform is trying to load kubectl from hashicorp provider: `- Finding latest version of hashicorp/kubectl...`

My project contains one module with resources from `hashicorp/kubernetes`

**Comment by zapo** [comment]
I had the same problem which pointed me to your comment. Make sure to redefine the source requirement in your module definition.
E.g.: mymodule/versions.tf
```
terraform {
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
    }
  }
}
```

The rationale is that modules can be reused across multiple projects and should be defining explicitly their dependencies.
Found the answer here https://github.com/hashicorp/terraform/issues/25995#issuecomment-685769082
I believe it's explained somewhere in terraform's docs modules section as well.

**Comment by gavinbunney** [comment]
Lots of discussion is available in this issue as well: https://github.com/gavinbunney/terraform-provider-kubectl/issues/39
