### ISSUE TITLE
kubectl provider seems to take only part (first part) the yaml

### ISSUE THREAD

**Issue by romankor** [gavinbunney/terraform-provider-kubectl#55]
Seems like that the `kubectl` provider catches only the part of the yaml ( before the `---`)

Here is an example.

```terraform 
resource "kubectl_manifest" "test" {
  yaml_body = <<YAML
apiVersion: v1
kind: Namespace
metadata:
  name: test1
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
YAML
}
```

and here is the plan : 
```
  # kubectl_manifest.test will be created
  + resource "kubectl_manifest" "test" {
      + api_version             = "v1"
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Namespace"
      + live_manifest_incluster = (sensitive value)
      + live_resource_version   = (known after apply)
      + live_uid                = (known after apply)
      + name                    = "test1"
      + namespace               = (known after apply)
      + resource_version        = (known after apply)
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<~EOT
            apiVersion: v1
            kind: Namespace
            metadata:
              name: test1
        EOT
      + yaml_incluster          = (sensitive value)
    }
```

I was using version 1.7.1 of the plugin, then I realized what is happening updated to 1.9.1 
TF version 13.0.4

Then again i don't see anyone complain about it , so it must be me ? 

---- 

Update:

ok having that in my code really messed everything up , the providers kept updating in the CI and when i ran TF locally i had the `1.7.2` version installed already and everything worked.
So CI was installing the latest version all the time 
```
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.2"
    }
```

I tracked it down to the latest working version which is : `1.7.2`

**Comment by rmasters** [comment]
I was having the same issue, but found the solution in #52. For multi-section YAML documents you need to use the `kubectl_file_documents` data-resource to parse out the individual documents first, and then iterate over them. For example, I was installing nginx-ingress:

```
data "kubectl_file_documents" "ingress_nginx_manifests" {
  content = file("k8s/ingress-nginx-controller-v0.40.2-digitalocean-deploy.yaml")
}

resource "kubectl_manifest" "nginx_ingress" {
  count = length(data.kubectl_file_documents.ingress_nginx_manifests.documents)
  yaml_body = element(data.kubectl_file_documents.ingress_nginx_manifests.documents, count.index)
}
```

You might need to update the kubectl provider as well. Hope this helps!

**Comment by gavinbunney** [comment]
@rmasters is correct :) If you want to use multi-doc, you'll need to either use the data resources or do a `split` for the yaml document separators (`---`)

**Comment by roock** [comment]
@gavinbunney May I suggest to improve documentation and clearly state that you should only include one yaml in one kubectl_manifest resource? There were two bug reports in the last month about that and I just stumbled upon the same issue.

**Comment by bmccutchon** [comment]
Or give an error instead of silently ignoring the rest of the file? I just spent several days debugging this...
