### ISSUE TITLE
kubectl apply for kustomization URL

### ISSUE THREAD

**Issue by marcellodesales** [gavinbunney/terraform-provider-kubectl#57]
# EKS Alb CRDs

* Based on https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller#tldr
* It's a directory with kustomization resources

```console
kubectl apply -k github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master
```

How can we apply in this case?

**Comment by gavinbunney** [comment]
Hi @marcellodesales, kustomization isn't support by this provider. For now, I would recommend preprocessing it, either out of band or via terraform `null_resource` to first render out the yaml files, then use the `kubectl_manifest` and `kubectl_path_documents` data source to then load the files

**Comment by marcellodesales** [comment]
@gavinbunney do you intend to implement that, or let users implement it? thank you!
