### ISSUE TITLE
The "count" value depends on resource attributes that cannot be determined

### ISSUE THREAD

**Issue by jbarop** [gavinbunney/terraform-provider-kubectl#58]
Hi,

`kubectl_path_documents` cannot be used with variables from other resources.

For example
```tf
data "kubectl_path_documents" "alb-ingress-controller" {
  pattern = "./alb-ingress-controller/*.yaml"
  vars = {
    vpc_id = module.vpc_id
  }
}

resource "kubectl_manifest" "alb-ingress-controller" {
  count     = length(data.kubectl_path_documents.alb-ingress-controller.documents)
  yaml_body = element(data.kubectl_path_documents.alb-ingress-controller.documents, count.index)
}
```

Leads to the following error:
```
 XX:   count     = length(data.kubectl_path_documents.manifests.documents)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

It would be nice if the variables could be passed to `kubectl_manifest`. Because in reality the count value does not depend on the vars. But terraform does not know that.

**Comment by jbarop** [comment]
Nevermind. I used the wrong property from the VPC module:

`vpc_id = module.vpc.vpc_id` (working) instead of `vpc_id = module.vpc.default_vpc_id` (not working)

**Comment by gavinbunney** [comment]
This is an issue with Terraform and depending on vars from other modules; it's unable to compute the graph correctly, as it doesn't known how many documents the `kubectl_path_documents` data resource will produce.

Two alternatives you can use are:

1/ Hardcode the count in your `kubectl_manifest` call - not great but works
2/ Add another `kubectl_path_documents` resource which just sets your var to an empty string, then use that only for the count element. Something like this:

```
data "kubectl_path_documents" "alb-ingress-controller" {
  pattern = "./alb-ingress-controller/*.yaml"
  vars = {
    vpc_id = module.vpc_id
  }
}

data "kubectl_path_documents" "alb-ingress-controller-count-hack" {
  pattern = "./alb-ingress-controller/*.yaml"
  vars = {
    vpc_id = ""
  }
}
resource "kubectl_manifest" "alb-ingress-controller" {
  count     = length(data.kubectl_path_documents.alb-ingress-controller-count-hack.documents)
  yaml_body = element(data.kubectl_path_documents.alb-ingress-controller.documents, count.index)
}
```

**Comment by yongzhang** [comment]
@gavinbunney As your second hack, is this the workaround for `kubectl_file_documents`?

```
data "template_file" "k8s_metrics_server" {
  template = file("templates/metrics-server.yaml")

  vars = {
    metrics_server_image_name    = "${var.docker_registry}/${var.metrics_server_image_name}"
    metrics_server_image_version = var.metrics_server_image_version
  }
}

data "kubectl_file_documents" "k8s_metrics_server" {
  content = data.template_file.k8s_metrics_server.rendered
}

data "kubectl_file_documents" "k8s_metrics_server_count_hack" {
  content = file("templates/metrics-server.yaml")
}

resource "kubectl_manifest" "k8s_metrics_server" {
  count            = length(data.kubectl_file_documents.k8s_metrics_server_count_hack.documents)

  yaml_body        = element(data.kubectl_file_documents.k8s_metrics_server.documents, count.index)
  wait_for_rollout = false
}
```

**Comment by andysousa** [comment]
@yongzhang did you get this hack working for `kubectl_file_documents`?

**Comment by yongzhang** [comment]
> @yongzhang did you get this hack working for `kubectl_file_documents`?

yes it’s ugly but works.

**Comment by hsalluri259** [comment]
> This is an issue with Terraform and depending on vars from other modules; it's unable to compute the graph correctly, as it doesn't known how many documents the `kubectl_path_documents` data resource will produce.
> 
> Two alternatives you can use are:
> 
> 1/ Hardcode the count in your `kubectl_manifest` call - not great but works
> 2/ Add another `kubectl_path_documents` resource which just sets your var to an empty string, then use that only for the count element. This way you still get a dynamic document count, but not depend on variables from other modules. Something like this:
> 
> ```
> data "kubectl_path_documents" "alb-ingress-controller" {
>   pattern = "./alb-ingress-controller/*.yaml"
>   vars = {
>     vpc_id = module.vpc_id
>   }
> }
> 
> data "kubectl_path_documents" "alb-ingress-controller-count-hack" {
>   pattern = "./alb-ingress-controller/*.yaml"
>   vars = {
>     vpc_id = ""
>   }
> }
> 
> resource "kubectl_manifest" "alb-ingress-controller" {
>   count     = length(data.kubectl_path_documents.alb-ingress-controller-count-hack.documents)
>   yaml_body = element(data.kubectl_path_documents.alb-ingress-controller.documents, count.index)
> }
> ```

I tried this for my issue, I still get the same error.
data "kubectl_path_documents" "controller_manifests" {
  pattern = "${path.module}/files/controller.yaml"
}

data "kubectl_path_documents" "controller_manifests_hack" {
  pattern = "${path.module}/files/controller.yaml"
  vars = {
    eks_cluster_name = ""
  }
}

resource "kubectl_manifest" "install_controller" {
  count     = length(data.kubectl_path_documents.controller_manifests.documents)
  yaml_body = element(data.kubectl_path_documents.controller_manifests.documents, count.index)
}
╰─ terraform apply
╷
│ Error: Invalid count argument
│
│   on modules/alb_controller/main.tf line 156, in resource "kubectl_manifest" "install_controller":
│  156:   count     = length(data.kubectl_path_documents.controller_manifests.documents)
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to
│ first apply only the resources that the count depends on.
╵

**Comment by marcinprzybysz86** [comment]
> This is an issue with Terraform and depending on vars from other modules; it's unable to compute the graph correctly, as it doesn't known how many documents the `kubectl_path_documents` data resource will produce.
> 
> Two alternatives you can use are:
> 
> 1/ Hardcode the count in your `kubectl_manifest` call - not great but works 2/ Add another `kubectl_path_documents` resource which just sets your var to an empty string, then use that only for the count element. This way you still get a dynamic document count, but not depend on variables from other modules. Something like this:
> 
> ```
> data "kubectl_path_documents" "alb-ingress-controller" {
>   pattern = "./alb-ingress-controller/*.yaml"
>   vars = {
>     vpc_id = module.vpc_id
>   }
> }
> 
> data "kubectl_path_documents" "alb-ingress-controller-count-hack" {
>   pattern = "./alb-ingress-controller/*.yaml"
>   vars = {
>     vpc_id = ""
>   }
> }
> 
> resource "kubectl_manifest" "alb-ingress-controller" {
>   count     = length(data.kubectl_path_documents.alb-ingress-controller-count-hack.documents)
>   yaml_body = element(data.kubectl_path_documents.alb-ingress-controller.documents, count.index)
> }
> ```

Hi @gavinbunney 
It doesn't work even if I dont need any vars. 
My code is just:

```
data "kubectl_path_documents" "docs" {
    pattern = "${path.module}/manifests/*.yaml"
} 

resource "kubectl_manifest" "argocd" {
    count     = length(data.kubectl_path_documents.docs.documents)
    yaml_body = element(data.kubectl_path_documents.docs.documents, count.index)
    override_namespace = "argocd"
}

│ Error: Invalid count argument
│
│   on modules\helm_argocd\main.tf line 13, in resource "kubectl_manifest" "argocd":
│   13:     count     = length(data.kubectl_path_documents.docs.documents)
│
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be

```

Any tips?
