### ISSUE TITLE
Disable string interpolation for YAML files

### ISSUE THREAD

**Issue by afedulov** [gavinbunney/terraform-provider-kubectl#65]
Hi, thanks for the provider!

It works nicely for the majority of my use cases, but I encountered an issue with this one (an ElasticSearch Operator):

https://github.com/elastic/cloud-on-k8s/blob/0d4106a2613a245a60ac59599ef473ade3a77988/deploy/eck-operator/templates/statefulset.yaml#L20

```
Error: failed to render ../all-in-one.yaml: <template_file>: (actual line numbers here) : Unknown variable; There is no variable named "data".
```

The issue is that the yaml file already happens to use the interpolation syntax:

```
[\"/var/log/containers/*${data.kubernetes.container.id}.log\"]
```

Is there a way to disable templating for particular resources or any other workarounds you could advice to try?

**Comment by gavinbunney** [comment]
Yes you can disable templating by setting `disable_template: true` :)
https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_path_documents#attribute-reference
