### ISSUE TITLE
Unable to download 1.9.2 / 1.9.3 / 1.9.4

### ISSUE THREAD

**Issue by bryantbiggs** [gavinbunney/terraform-provider-kubectl#66]
As the title says, I get failures if specifying anything above `1.9.1` 

```bash
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
gavinbunney/kubectl: no available releases match the given constraints 1.9.4,
1.9.1
```

**Comment by gavinbunney** [comment]
Hi @bryantbiggs can you post your versions.tf or how you're defining the versions in your terraform project? Seems like a TF v0.13.x or v.14.x specific issue rather than with this provider specifically
