### ISSUE TITLE
Problem to apply a yaml file in a defined namespace.

### ISSUE THREAD

**Issue by opotmans** [gavinbunney/terraform-provider-kubectl#67]
Hello,
In the context of the automation of the deployment of the bookinfo application for Istio 1.9, I would like to use your provider kubectl with the resource kubectl_manifest

Versioning:
- Using previously-installed hashicorp/azurerm v2.39.0
- Using previously-installed hashicorp/kubernetes v1.13.3
- Using previously-installed hashicorp/random v3.0.0
- Using previously-installed hashicorp/local v2.0.0
- Using previously-installed hashicorp/null v3.0.0
- Using previously-installed gavinbunney/kubectl v1.9.4

Code objective 
1. create a namespace based on a name defined in the variable which is transferred via the module
2. apply the bookinfo.yaml file (located in the YAML_files directory ) using the resource kubectl manifest and install it in the namespace defined in the previous point

Remark: the bookinfo.yaml file is extracted from : https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/bookinfo.yaml 

Here is the code:
// use the provider kubernetes
provider "kubernetes" {
load_config_file = "false"
host = var.aks_host
username = var.aks_username
password = var.aks_password
client_certificate = base64decode(var.aks_client_certificate)
client_key = base64decode(var.aks_client_key)
cluster_ca_certificate = base64decode(var.aks_ca_certificate)
}

resource "kubernetes_namespace" "env" {
  metadata {
    name = var.environment
    labels = {
      istio-injection = "enabled"
    }
  }
}

//use the provider kubectl
provider "kubectl" {
  load_config_file = "false"
  host = var.aks_host
  username = var.aks_username
  password = var.aks_password
  client_certificate = base64decode(var.aks_client_certificate)
  client_key = base64decode(var.aks_client_key)
  cluster_ca_certificate = base64decode(var.aks_ca_certificate)
}

resource "kubectl_manifest" "bookinfo" {
  override_namespace = var.environment
  yaml_body = file ("${path.module}/YamlFiles/bookinfo.yaml")
  depends_on = [kubernetes_namespace.env]
}

However the installation doesn't work and the pods are not created in the namespace defined by the argument neither in another namespace.

Could you please help me ?

Thanks in advance for your support

Olivier

**Comment by jodem** [comment]
Hi that's because you are using a multi-line yaml, and with version higher than 1.7.2  you cannot have more than one yaml definition per file otherwise you have to use a datasource object : https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_file_documents

It's not even failing it just says applied but only the 1rst part of the doc is applied.

Honestly I don't understand why the multi-yaml document are not supported anymore by design, it breaks a lot of things in my stacks, I spent 5+ hours debugging workmate stack before finding that out. And I have many hours to come to migrate my stack to the next format.

**Comment by yuriyfilonovooh** [comment]
Thanks for responding @jodem New syntax works, though seems a bit weird:

Wouldn't it make more sense to use `yaml_body=data.kubectl_file_documents.keel.content` with configuration like this one:

```
data "kubectl_file_documents" "keel" {
    content = file("kubernetes/keel.yaml")
}

resource "kubectl_manifest" "keel" {
    count = length(data.kubectl_file_documents.keel.documents)
    yaml_body = element(data.kubectl_file_documents.keel.documents, count.index)
}
```
