### ISSUE TITLE
Feature request: sensitve yaml_body content

### ISSUE THREAD

**Issue by lukasmrtvy** [gavinbunney/terraform-provider-kubectl#7]
**Problem:** 
Usualy I am using remote state backend and TF is running in CI pipeline, but its very risky to output these secrets to stdout...

**Options:**
Would be super useful ( crucial feature for me ) to have `yaml_body_sensitive` option as input for resource to hide manifest/manifest change in diff ( apply/plan/destroy ).

Maybe some auto hiding when `kind = Secret` would do the job, or custom input filter like `sensitive_kinds=[]` for CRDs...

Another possible option ( best, but hardest ) would be to specify input map like `secrets = {}`  with secrets and do the templating inside the provider and expose whole manifest with obfuscated values.

**Use case:**
Template manifest files with secrets with terraform ( datasourced from other resources ) and deploy to k8s.

**Alternative providers with hidding support:** 
Even official kubernetes provider and `kubernetes_secret` resource is hiding whole secret's `data` value.

**Comment by gavinbunney** [comment]
@lukasmrtvy Finally got some time to work on this.... and it's in v1.6.0 now 🎉 

Docs: https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/manifest#sensitive-fields
