### ISSUE TITLE
resource [kustomize.config.k8s.io/v1beta1/Kustomization] isn't valid for cluster, check the APIVersion and Kind fields are valid

### ISSUE THREAD

**Issue by fsaryazdi** [gavinbunney/terraform-provider-kubectl#71]
I am trying to deploy efs-csi-driver on my cluster using the aws documentation: 
https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

Here's my manifest and kustomization.yaml file: 

resource "kubectl_manifest" "mf_efs_driver" {
    yaml_body = <<YAML
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    bases:
      - ../../../base
    images:
      - name: amazon/aws-efs-csi-driver
        newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver
        newTag: v1.0.0
      - name: quay.io/k8scsi/livenessprobe
        newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe
        newTag: v2.0.0
      - name: quay.io/k8scsi/csi-node-driver-registrar
        newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar
        newTag: v1.3.0
    YAML
}

But seems like there's no support for it. Is there any workaround you would suggest?

**Comment by gavinbunney** [comment]
Hi @fsaryazdi, the `kustomization` file format isn't valid for applying to a kubernetes cluster directly. You'll need to preprocess that into yaml files before applying it with the `kubectl_manifest` resource, e.g. `kustomize -b . > resources.yaml`

**Comment by AlecZebrick** [comment]
@gavinbunney Hello I'm having a the same issue. What do you mean by preprocess? I have kustomize installed but not really sure what the -b flag is doing here?
