### ISSUE TITLE
Add kubectl_file_documents id

### ISSUE THREAD

**Issue by phillebaba** [gavinbunney/terraform-provider-kubectl#72]
Splitting a multidoc yaml into separate resources works well with the current provider, but has its issues when updating the manifests. Using count requires the ordering to never change, and if it does it will force a recreation of all the resources that are out of order. Using a for_each and the hash value of the content as a key as the same issues but for inidivual resources, so the ordering no longer matters.

Would it not be easier to expose the id in the same format as kubectl_manifest has together with the documents. That way we would be able to make sure that it is the same resource which is being updated. It would look something like this.
```
resource "kubectl_manifest" "example" {
  for_each   = { for v in data.kubectl_file_documents.example.documents : v.id => v.content }
  yaml_body = each.value
}
```

It could be added as a new data source to keep backwards compatibility.

**Comment by gavinbunney** [comment]
Hi @phillebaba I like that idea! In a few of our larger terraform projects we indeed do a bunch of looping over counts; moving to dynamic will make adding _new_ resources to existing files also work without having to apply/delete loop over everything.

Today the yaml parser on the documents reader just ensures that it's valid YAML - would need to expand that to validate that it's a valid k8s yaml, then extract the id/selfLink portions to make this possible

**Comment by phillebaba** [comment]
I will have a look at the code over the next week and see if it works better than the current solution of creating this ID myself. If its easy and works it might be a safer solution.

**Comment by mhulscher** [comment]
> Using a for_each and the hash value of the content as a key as the same issues but for inidivual resources, so the ordering no longer matters.

Will using the content hash not lead to manifests being re-created every time the content changes? Because their ID changes? I would not want that to happen for CRDs for example.

**Comment by dghubble** [comment]
The core problem seems to be that `kubectl_file_documents` and `kubectl_path_documents` only provide a `documents` list of Kubernetes manifest. Any time manifests are added or removed, it disturbs the indexing, causing needless creates/deletes.

For solutions, if the provider had only supported one-manifest-per-file, a stable map could have been made just associating filepaths to contents (e.g. hypothetical `documents_map` maps filepath to Kubernetes manifest content) and used as follows:

```hcl
resource "kubectl_manifest" "example" {
  for_each   = { for path, content in data.kubectl_file_documents.example.documents_map : path => content }
  yaml_body = each.value
}
```

But this provider allows many-manifests-per-file, it would be more complicated. You'd need to try to have a `documents_maps` map filepath to list of Kubernetes manifests. (Or just say this is unsupported and store the first manifest only).

```hcl
# roughly something like this
resource "kubectl_manifest" "example" {
  for_each   = { 
    for path, manifests in data.kubectl_file_documents.example.documents_map : merge({
       for i, manifest => "${path}-${i}" => manifest
    })
  }
  yaml_body = each.value
}
```

**Comment by dghubble** [comment]
@mhulscher yeah, using a content hash as an id would cause create/delete on every change. Definitely not desired vs letting Terraform show the diff

**Comment by nyurik** [comment]
@gavinbunney is it documented anywhere how the `id` is formed from the manifests?  In theory it should include API, Kind, namespace, and the name to be purely identical, but I might be mistaken.
