### ISSUE TITLE
Document YAML single-doc restriction of kubectl_manifest

### ISSUE THREAD

**Issue by sampierson** [gavinbunney/terraform-provider-kubectl#74]
I just lost a day debugging why only the first resource in my my multi-doc YAML manifest got applied by `kubectl_manifest`.  After taking apart the kubectl-provider and isolating the issue, I finally found out it is a known issue, but the only documentation I can find on it is a comment on a mostly-unrelated GitHub issue https://github.com/gavinbunney/terraform-provider-kubectl/issues/67#issuecomment-747293098 (many thanks to @jodem).

I am not the only one who has lost time to this "feature".  Please please please can you document this restriction on the `kubectl_manifest` resource page, and have that mention, or even link to, the `kubectl_file_documents` page.

**Comment by gavinbunney** [comment]
Added a note to the docs. Thanks!
