### ISSUE TITLE
kubernetes deployment rollback scenario

### ISSUE THREAD

**Issue by jungwookim** [gavinbunney/terraform-provider-kubectl#75]
Hi, I've been working on k8s deployment using Terraform. So this provider is great to use the existing yamls. I was wondering if there is a `rollout undo` (rollback) method or how does it work in the provider? 

```terraform
resource "kubectl_manifest" "target" {
  yaml_body = <<<YAML
  ...kubernetes deployment yaml
  YAML
}
```
`terraform apply -var='image=${image}' -var-files=${env}.tfvars -target="kubectl_manifest.target"-auto-approve`

I'm using the above for it but I have no idea what if this `apply` is failed.

**Comment by whiskeysierra** [comment]
I'd expect that a cleanup/rollback is done if you remove that resource from your module. Like with any other terraform resource.

**Comment by gavinbunney** [comment]
Hi @jungwookim as @whiskeysierra mentioned, to "undo" the rollout the options you have is to revert the yaml and/or delete the resource. The provider tracks the current state of the deployment, so reapplying with the "rolled back" yaml will cause it to be reverted. There isn't any direct support for doing a `rollout undo` as it breaks the terraform state machine assumptions
