### ISSUE TITLE
provider "host" property ignored

### ISSUE THREAD

**Issue by SignalRichard** [gavinbunney/terraform-provider-kubectl#76]
Hi,

I've encountered an issue where the host property is ignored in the kubectl provider.  I get the following error when attempting to apply a plan with the host property set to `127.0.0.1:8001`:

`Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.`

The error appears to indicate that it tried to connect on port `80` instead of `8001`.  If I run `kubectl proxy --port 80` instead of allowing it to use the default port the plan will successfully apply.

Here are the rest of the environment details:
Windows 10 version 1909
Docker Desktop 3.1.0 (51484)
Kubernetes cluster:
`minikube start --memory 2536mb --driver=docker --kubernetes-version=1.19.0 -p cluster1`
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
terraform version:
```
Terraform v0.14.5
+ provider registry.terraform.io/fluxcd/flux v0.0.11
+ provider registry.terraform.io/gavinbunney/kubectl v1.10.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
```

And for reference here is the terraform script being applied:
```
terraform {
  required_version = ">= 0.13"

  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 1.13.3"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.9.1"
    }
    flux = {
      source  = "fluxcd/flux"
      version = ">= 0.0.7"
    }
  }
}

provider "flux" {}

provider "kubectl" {
  host = "127.0.0.1:8001"
}

# Flux
data "flux_install" "main" {
  target_path = var.target_path
}

# Kubernetes
resource "kubernetes_namespace" "flux_system" {
  metadata {
    name = "flux-system"
  }
}

data "kubectl_file_documents" "install" {
  content = data.flux_install.main.content
}

resource "kubectl_manifest" "install" {
  for_each   = { for v in data.kubectl_file_documents.install.documents : sha1(v) => v }
  depends_on = [kubernetes_namespace.flux_system]

  yaml_body = each.value
}
```

**Comment by gavinbunney** [comment]
Hi @SignalRichard I believe this is due to missing the scheme in the host uri. The kubeconfig is a little picky, so this should work for you:

```
provider "kubectl" {
  host = "http://127.0.0.1:8001"
}
```
