### ISSUE TITLE
Lazy provider initialization

### ISSUE THREAD

**Issue by caruccio** [gavinbunney/terraform-provider-kubectl#77]
Hi.

I'm facing this error during planning:

```
Planning... [/state.run/provider/terraform.plan]

Error: failed to load config (/getup-engine/.kube/config; default context): invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

This happens because there is no kubernetes cluster yet, so there is no auth data to read from.

Is there any way to postpone the init phase or even ignore failed read operations?

**Comment by caruccio** [comment]
AFAIU, helm provider will only store provider config values [[1]](https://github.com/hashicorp/terraform-provider-helm/blob/921639880e34a9bb15bab243ab69b44751f4963a/helm/provider.go#L227) and load kubeconfig during operations [[2]](https://github.com/hashicorp/terraform-provider-helm/blob/921639880e34a9bb15bab243ab69b44751f4963a/helm/resource_release.go#L404) and [[3]](https://github.com/hashicorp/terraform-provider-helm/blob/921639880e34a9bb15bab243ab69b44751f4963a/helm/provider.go#L312)
FYI, my golang-foo is not that good.

**Comment by whiskeysierra** [comment]
Isn't this what `load_config_file` is for?

```hcl
provider "kubectl" {
  host                   = var.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(var.eks_cluster_ca)
  token                  = data.aws_eks_cluster_auth.main.token
  load_config_file       = false
}
```

**Comment by caruccio** [comment]
@whiskeysierra thanks!! I was missing some dependencies from kind's output.
