### ISSUE TITLE
Kubernetes cluster unreachable when performing Terraform Destroy

### ISSUE THREAD

**Issue by lpossamai** [gavinbunney/terraform-provider-kubectl#79]
When trying to destroy an existing AWS EKS cluster with `terraform destroy`, I get the following error:

```
helm_release.eks_cluster_test: Destroying... [id=eks_cluster_test]

Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

`kubectl get nodes` works. It's only via Terraform that is not working.

```
provider "kubectl" {
  source  = "gavinbunney/kubectl"
  version = "1.10.0"
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
}
```

Any idea what am I doing wrong, please?

**Comment by countablecloud** [comment]
this stopped working for me too. i dont think its an issue with the kubectl provider directly; think its a broader problem w underlying kubernetes provider. i switched to using this provider configuration for kubernetes, kubectl, and helm and it fixed all of them.

` host                   = module.eks.host
  cluster_ca_certificate = base64decode(module.eks.cluster-ca-certificate)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["eks", "get-token", "--cluster-name", var.name]
    command     = "aws"
  }`

**Comment by lpossamai** [comment]
> this stopped working for me too. i dont think its an issue with the kubectl provider directly; think its a broader problem w underlying kubernetes provider. i switched to using this provider configuration for kubernetes, kubectl, and helm and it fixed all of them.

But what's the `kubectl` provider you're using, if not `gavinbunney`?

**Comment by lpossamai** [comment]
Yeah, [apparently that's how you're supposed to use it](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) against EKS. 

```
provider "kubectl" {
  apply_retry_count      = 15
  host                   = var.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(var.eks_cluster_ca)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws-iam-authenticator"
    args = [
      "token",
      "-i",
      module.eks.cluster_id,
    ]
  }
}
```

It doesn't work for me, though. Same error.

`data_imports.tf`:

```
data "aws_eks_cluster" "cluster" {
  name = "${terraform.workspace}-cluster"
}
```

`providers.tf`:

```
provider "kubectl" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)

  exec {
      api_version = "client.authentication.k8s.io/v1alpha1"
      args        = ["eks", "get-token", "--cluster-name", data.aws_eks_cluster.cluster.name]
      command     = "aws"
    }

  load_config_file       = false
}
```

If I run `aws eks get-token --cluster-name stage-cluster` I get a successful response.

**Comment by ellisio** [comment]
We're getting this error, but for GCP, when running `terraform destroy`. However, this only happens after a few hours after a `terraform apply` was initially ran.

If we run a `terraform apply`, followed up by an immediate `terraform destroy` everything is good. If we run a `terraform apply`, and then wait a couple hours, then run a `terraform destroy`, that is when this error starts happening.

### Error
```
Error: letsencrypt-staging failed to create kubernetes rest client for delete of resource: Unauthorized
```

### Terraform Config

This is how we have our stack configured, which was pulled from the [official documentation for Kubernetes](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform#using-the-kubernetes-and-helm-providers):

```
data "google_client_config" "default" {}

data "google_container_cluster" "apps" {
  project  = var.project_id
  name     = var.cluster_name
  location = var.cluster_region
}

provider "kubectl" {
  load_config_file       = false
  host                   = "https://${data.google_container_cluster.apps.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.apps.master_auth[0].cluster_ca_certificate)
}

resource "kubectl_manifest" "issuer_http_staging" {
  yaml_body  = file("${path.module}/issuers/http-staging.yaml")
}
```

**Comment by whiskeysierra** [comment]
> and then wait a couple hours, then run a `terraform destroy`, that is when this error starts happening.

Just a hunch, but my best bet would be that `data.google_client_config.default.access_token` expired in the meantime.

**Comment by whiskeysierra** [comment]
AKS has that *"problem"*. See https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/_examples/aks/README.md#replacing-the-aks-cluster-and-re-creating-the-kubernetes--helm-resources

**Comment by lpossamai** [comment]
Hi all. 

This has been working for me for a couple of days now. All I did was `terraform init` again and it started working. I'll close this ticket now.

**Comment by weiwuprojects** [comment]
What fixed it for me was setting `export KUBE_CONFIG_PATH=~/.kube/config`

**Comment by janibashamd** [comment]
what's the final solution here ?
