### ISSUE TITLE
Match hashicorp/kubernetes provider behaviour when running inside of a cluster.

### ISSUE THREAD

**Issue by ctibsc** [gavinbunney/terraform-provider-kubectl#80]
When `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` have non-empty values the hashicorp/terraform provider will try to use the service account token in `/var/run/secrets/kubernetes.io/serviceaccount/token`.  Is it possible to replicate the same behavior for this provider?

**Comment by gavinbunney** [comment]
Hi @ctibsc this is actually a feature of the underlying go-client sdk. It should be supported today. You may need to update to use the latest provider (v1.11.0+) to get the latest k8s sdk version in there.

An empty provider configuration something like this should work:

```
```hcl
provider "kubectl" {
}
```
```
