### ISSUE TITLE
Kubernetes Provider v2 Support

### ISSUE THREAD

**Issue by kskumgk63** [gavinbunney/terraform-provider-kubectl#81]
Hi,

Any plans to support the new `v2.0.x` Kubernetes provider?

v2 upgrade guide is https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide

**Comment by whiskeysierra** [comment]
I'm confused. The terraform-provider-kubectl (this repo here) does not depend on the official kubernetes provider, does it?

**Comment by kskumgk63** [comment]
I see. I was actually asking a question without really understanding it. Sorry.

I was wondering if arguments should be matched with the official kubernetes provider.
For example, `load_config_file` is dropped in v2 kubernetes provider.

**Comment by gavinbunney** [comment]
Thanks @kskumgk63 ! Updated the docs and synchronized the flag differences.
https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#argument-reference
