### ISSUE TITLE
Support for Files instead of manifests

### ISSUE THREAD

**Issue by kandji-leon** [gavinbunney/terraform-provider-kubectl#85]
Any chance this could support files, with multiple manifests instead of just a single manifest.

**Comment by whiskeysierra** [comment]
That's already supported: https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_file_documents

**Comment by gavinbunney** [comment]
Thanks @whiskeysierra !

The other helpful data resource is `kubectl_path_documents`: https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_path_documents
