### ISSUE TITLE
Incosistent Final Plan

### ISSUE THREAD

**Issue by vikaskoppineedi** [gavinbunney/terraform-provider-kubectl#90]
Error: Provider produced inconsistent final plan
When expanding the plan for kubectl_manifest.apply-fluentd-cloudwatch[2] to
include new values learned so far during apply, provider
"registry.terraform.io/gavinbunney/kubectl" produced an invalid new value for
.yaml_incluster: inconsistent values for sensitive attribute.

**Comment by vikaskoppineedi** [comment]
My terraform plan says **Plan: 3 to add, 58 to change, 22 to destroy.** and it fails to update saying provider produces inconsistent final plan.  I am removing this provider from my terrform code. so many unknown surprises.

**Comment by mcwienczek-rtl** [comment]
I am having similar issue. It started when I added `sensitive_fields` attribute.

**Comment by tehlers320** [comment]
Getting this as well, i did not add sensitive_fields just a simple namespace yaml template from a data source.

```
data "template_file" "namespace" {
  template = file("${path.module}/files/namespace.yaml.tpl")
  vars = {
    namespace = var.fnamespace
  }
}

resource "kubectl_manifest" "namespace" {
  yaml_body = data.template_file.namespace.rendered
}
```

k8s version 1.17
terraform-provider-kubectl 1.10.0

**Comment by tehlers320** [comment]
destroying the resource then adding this fixed it for me.

```
  ignore_fields = [
    "metadata.labels",
    "metadata.annotations",
  ]
```

**Comment by tehlers320** [comment]
The problem is very odd, i cannot change any field at all. I've ignored virtually every field i could. 

Is this the same error you are both seeing? 
```
This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021/04/30 09:00:56 [ERROR] eval: *terraform.EvalSequence, err: Provider produced inconsistent final plan: When expanding the plan for module.federated-helm-controller.kubectl_manifest.fhc_artifactory_repo to include new values learned so far during apply, provider "registry.terraform.io/gavinbunney/kubectl" produced an invalid new value for 
.yaml_body_parsed: 
was cty.StringVal("apiVersion: types.kubefed.io/v1beta1\nkind: FederatedHelmRepository\nmetadata:\n  name: coolthing\n  namespace: coolnamespace\nspec:\n  placement:\n    clusterSelector:\n      matchLabels: {}\n  template:\n    spec:\n      interval: 5m0s\n      secretRef:\n        name: somename\n      timeout: 1m0s\n      url: https://someurl/\n"), 
but now cty.StringVal("apiVersion: types.kubefed.io/v1beta1\nkind: FederatedHelmRepository\nmetadata:\n  name: coolthing\n  namespace: coolnamespace\nspec:\n  placement:\n    clusterSelector:\n      matchLabels: {}\n  template:\n    spec:\n      interval: 5m0s\n      secretRef:\n        name: somename\n      tim: \"true\"\n      timeout: 1m0s\n      url: https://someurll/\n").
```

**Comment by gavinbunney** [comment]
Can you provide any output from running with `TF_LOG=TRACE`? It's a little hard to debug without seeing the different yaml outputs. The provider emits a log lines for sensitive values, as well as yaml drift detection and Unstructured YAML which provides details around what it's doing internally. Feel free to reopen with more details. Thanks!
