### ISSUE TITLE
kubectl_filename_list, what determines the order in which they are applied?

### ISSUE THREAD

**Issue by trudesea** [gavinbunney/terraform-provider-kubectl#96]
Hi,

I have about 12 manifests to apply, some have dependencies on others and I need to apply them in a certain order.  I named the files like so: xxxxx.0.yaml, xxxxx.1.yaml...... and so on but it doesn't seem to go in file listing order, not sure what determines the order. 

Is there a way to do this or am I just going to have to have a section of code for each manifest using kubectl_file_documents?

Thanks

**Comment by jessequinn** [comment]
any progress on this @trudesea?

**Comment by trudesea** [comment]
Hi,
I think I figured it out, it seems to go in file listing order based on filename but I'm not 100% and wanted someone in the know to confirm.  It's hard for me to tell in the output on the terraform apply 

For now it is working for me.

**Comment by gavinbunney** [comment]
Hi @trudesea,

The way I handle this locally is to prefix the file names with numbers, e.g. `01-first.yaml`, `02-second.yaml`. Then in the `kubectl_path_documents` resource (will work the same for the filename_list resource, use a pattern match to select those `01-*` yaml files first:

```
data "kubectl_path_documents" "fluentbit-config" {
  pattern = "${path.module}/fluentbit/src/01-*.yaml"
}
```

This allows you to have multiple `01-*` files and apply them in batches.

There is an open issue #72 to provide an id, so you can then use the `for_each` statements a bit easier as well.
