### ISSUE TITLE
Is it worth linking to the 1.10 terraform kubernetes provider docs?

### ISSUE THREAD

**Issue by bynare** [gavinbunney/terraform-provider-kubectl#97]
[The config documentation](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#configuration) refers to the kubernetes provider's documentation, but by the looks it should be referring to an older version of that documentation?

I.e `load_config_file` is no longer documented [there](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs), but still works for this provider.

Is this provider's version linked to the kubernetes provider's version?

Let me know if you want me to have a crack at updating the docs?

Thanks for this cool tool btw :)

**Comment by stevehipwell** [comment]
Should `load_config_file` be removed from this module to align with the Kubernetes provider?

**Comment by gavinbunney** [comment]
Thanks @bynare ! Updated the docs and synchronized the flag differences.
https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#argument-reference

I ended up keeping the `load_config_file` as I find it useful in my environments :)
